;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Data.Damage.DamageOvertime",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Changed",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Claw",DevComment="")
+GameplayTagList=(Tag="Event.Montage.ComboHit",DevComment="")
+GameplayTagList=(Tag="Gameplay.Attack.UsingClaw?",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="State.Death",DevComment="")
+GameplayTagList=(Tag="Status.Death",DevComment="")
+GameplayTagList=(Tag="Status.Health.Regen",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")

